CREATE TABLE students(
  	sr INTEGER,
	VCAA_CODE INTEGER,
	SCHOOL_NAME	VARCHAR(255) NOT NULL,
	SECTOR VARCHAR(2),
	LOCALITY VARCHAR(255) NOT NULL,	
	TOTAL_COMPLETED_YEAR_12 INTEGER,	
	ON_TRACK_CONSENTERS INTEGER,	
	ON_TRACK_RESPONDENTS INTEGER,
	BACHELOR_ENROLLED	INTEGER,
	DEFERRED INTEGER,	
	TAFE_VET_ENROLLED INTEGER,	
	APPRENTICE_TRAINEE INTEGER,	
	EMPLOYED	INTEGER,
	LOOKING_FOR_WORK INTEGER,
	Other INTEGER,
	PRIMARY KEY (SCHOOL_NAME,LOCALITY)

);

select * from students